---
- name: Create devops group
  ansible.builtin.group:
    name: devops
    state: present

- name: Add devops user
  ansible.builtin.user:
    name: "{{ item.name }}"
    group: devops
  with_items: "{{ devops }}"

- name: Set authorized keys taken from url
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.ssh_keys }}"
  with_items: "{{ devops }}"
...
