---
- name: Create a /home/{{ user.name }}/.config/i3 directory if it does not exist
  ansible.builtin.file:
    path: "/home/{{ user.name }}/.config/i3"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    state: directory
    mode: '0755'

- name: Copy the i3 config
  ansible.builtin.copy:
    src: "config"
    dest: "/home/{{ user.name }}/.config/i3/config"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0644"
...
