---
# tasks file for gui
- name: Install GUI packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  loop:
    - "papirus-icon-theme"
    - "brightnessctl"
    - "xclip"
    - "hsetroot"
    - "rofi"
    - "maim"
    - "xorg"
    - "xorg-xinit"
    - "xorg-server"
    - "i3-wm"
    - "i3lock"
    - "i3status"
    - "dmenu" 
    - "lightdm"
    - "lightdm-gtk-greeter"

- include_tasks: i3.yaml
- include_tasks: rofi.yaml
- include_tasks: wallpaper.yaml
- include_tasks: xinit.yaml

- name: Copy the face
  ansible.builtin.copy:
    src: "face.png"
    dest: "/home/{{ user.name }}/.face.png"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0644"

- name: Enable service lightdm
  ansible.builtin.service:
    name: "lightdm.service"
    state: started
    enabled: yes
  when: yes
...
