---
- name: Create a .config/rofi directory if it does not exist
  ansible.builtin.file:
    path: "/home/{{ user.name }}/.config/rofi"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    state: directory
    mode: '0755'

- name: Copy the configuration of rofi
  ansible.builtin.copy:
    src: "config.rasi"
    dest: "/home/{{ user.name }}/.config/rofi/"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0644"
...
