---
# Kitty
- name: Install the last version of kitty
  ansible.builtin.package:
    name: "kitty"
    state: latest

- name: Create a .config/kitty directory if it does not exist
  ansible.builtin.file:
    path: "/home/{{ user.name }}/.config/kitty"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    state: directory
    mode: '0755'

# Copy the theme
- name: Copy the theme
  ansible.builtin.copy:
    src: "theme.conf"
    dest: "/home/{{ user.name }}/.config/kitty/theme.conf"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0644"

# Copy the configuration
- name: Copy the configuration
  ansible.builtin.template:
    src: "kitty.conf.j2"
    dest: "/home/{{ user.name }}/.config/kitty/kitty.conf"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0644"
...
