---
# tasks file for i3
- name: Install a GUI packages
  become: yes
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  loop:
    - "xorg-xinit"
    - "xorg-server"
    - "i3-wm"
    - "i3status"
    - "dmenu" 
    - "lightdm"
    - "lightdm-gtk-greeter"

- name: Copy the xinitrc
  become: yes
  ansible.builtin.copy:
    src: "xinitrc"
    dest: "/home/{{ user.name }}/.xinitrc"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0644"

- name: Create a /home/{{ user.name }}/.config/i3 directory if it does not exist
  become: yes
  ansible.builtin.file:
    path: "/home/{{ user.name }}/.config/i3"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    state: directory
    mode: '0755'

- name: Copy the i3 config
  become: yes
  ansible.builtin.copy:
    src: "config"
    dest: "/home/{{ user.name }}/.config/i3/config"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0644"
...
