---
# tasks file for vim

- name: Install the last version of vim
  become: yes
  ansible.builtin.package:
    name: "vim"
    state: latest

- name: Copy the vimrc
  become: yes
  ansible.builtin.copy:
    src: "vimrc"
    dest: "/home/{{ user.name }}/.vimrc"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0644"

- name: Copy the vim folder
  become: yes
  ansible.builtin.copy:
    src: "vim"
    dest: "/home/{{ user.name }}/.config/"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0644"

- name: Copy the personnal information
  become: yes
  ansible.builtin.template:
    src: "personnal-info.vimrc.j2"
    dest: "/home/{{ user.name }}/.config/vim/personnal-info.vimrc"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0644"

- name: Create a .vim directory if it does not exist
  become: yes
  ansible.builtin.file:
    path: "/home/{{ user.name }}/.vim/autoload"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    state: directory
    mode: '0755'

- name: Upload the plugin manager via get url
  become: yes
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "/home/{{ user.name }}/.vim/autoload/plug.vim"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0644"

- name: Upload the theme cyberpunk via get url
  become: yes
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/Roboron3042/Cyberpunk-Neon/master/terminal-apps/vim/cyberpunk-neon.vim
    dest: "/home/{{ user.name }}/.vim/autoload/cyberpunk-neon.vim"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0644"
...
