---
# tasks file for grub

- name: Copy the grub font
  ansible.builtin.copy:
    src: "grubfont.pf2"
    dest: "/boot/grubfont.pf2"
    owner: "root"
    group: "root"
    mode: "0644"

- name: Add a line to grub if the file does not exist, without passing regexp
  ansible.builtin.blockinfile:
    marker_begin: GRUB SONG
    marker_end: GRUB SONG END
    path: "/etc/default/grub"
    backup: yes
    block: |
      GRUB_INIT_TUNE="1750 523 1 392 1 523 1 659 1 784 1 1047 1 784 1 415 1 523 1 622 1 831 1 622 1 831 1 1046 1 1244 1 1661 1 1244 1 466 1 587 1 698 1 932 1 1195 1 1397 1 1865 1 1397 1"
      GRUB_FONT="/boot/grubfont.pf2"
    create: no

- name: Remake a grub config
  ansible.builtin.command:
    cmd: "grub-mkconfig -o /boot/grub/grub.cfg"
